workspace:
  path: /got

pipeline:
  test:
    image: gitlab/dind
    commands:
      - pwd
      - docker --version
      - docker-compose --version
      - ls -la
      - ls -la $(pwd)
      - docker ps
      - docker-compose run module ls -la
      - docker ps
      - docker-compose run --rm module yarn install
      - docker-compose run --rm module yarn test
    secrets: [ CODECLIMATE_REPO_TOKEN ]
    environment:
      - DOCKER_DRIVER=overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
